version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install
          command: yarn --frozen-lockfile --non-interactive
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:coverage
